name: flapper
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  bloc: ^9.0.0
  build_when: ^0.1.1
  cached_network_image: ^3.4.1
  ephemeral_value: ^1.3.0
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  flutter_local_notifications: ^19.4.2
  flutter_localizations:
    sdk: flutter
  go_router: ^16.0.0
  google_fonts: ^6.3.0
  http: ^1.4.0
  intl: ^0.20.2
  material_color_utilities: ^0.11.1
  path_provider: ^2.1.5
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  supabase_flutter: ^2.10.0
  timeago: ^3.7.1
  toastification: ^3.0.3
  url_launcher: ^6.3.2
  gradient_borders: ^1.0.2
  gpt_markdown: ^1.1.4
  syntax_highlight: ^0.5.0
  web: ^1.1.0
  flutter_secure_storage: ^10.0.0-beta.5
  boxy: ^2.2.2
  hydrated_bloc: ^10.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^10.0.0
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/
    - assets/google_fonts/